### ISSUE TITLE
Bug: patterned glasses and panes are registering as wood variants when you walk on them

### ISSUE THREAD

**Issue by EGOIST1372** [ReviversMC/patterned-glass#3]
patterned glasses and panes are registering as both wood and glass variants when you walk on them base on the sound subtitle(wood creaks)
maybe incompatible with [presence footsteps](https://www.curseforge.com/minecraft/mc-mods/presence-footsteps) mod
![image](https://user-images.githubusercontent.com/86555131/154727989-782cbdff-17f6-4a18-8e9e-3e6bc08c2c05.png)

**Comment by NebelNidas** [comment]
Can be easily fixed by adding a [blockmap.json](https://github.com/Sollace/Presence-Footsteps/wiki/Resourcepacks:-Blockmap.json)
